# Exercise One

## 1. Implement this algorithm in Python. 

Use the NumPy ndarray object for your matrices;

In [9]:
import time
import numpy as np


def multiply_matrices(A, B):
    dimension = A.shape[0]
    Result = np.zeros((dimension, dimension), dtype=int)
    for i in range(dimension):
        for j in range(dimension):
            Result[i, j] = sum(A[i, k] * B[k, j] for k in range(dimension))
    return Result

### Implementation and Comparison

In [5]:
Matrix_A = np.array([[2, 4], [6, 8]])
Matrix_B = np.array([[1, 3], [5, 7]])
Matrix_C = np.array([[3, 2, 7, 5], [10, 7, 3, 6], [5, 1, 3, 6], [2, 3, 8, 7]])
Matrix_D = np.array([[i for i in range(1, 8)] for _ in range(7)])

print("Results using NumPy's matmul:")
start = time.time()
print('2 x 2 Matrix:', np.matmul(Matrix_A, Matrix_B))
print('4 x 4 Matrix:', np.matmul(Matrix_C, Matrix_C))
print('5 x 5 Matrix:', np.matmul(Matrix_D, Matrix_D))
run_time = time.time() - start
print('time: ', run_time)

start = time.time()
print("Results using custom matrix multiplication function:")
print('2 x 2 Matrix:', multiply_matrices(Matrix_A, Matrix_B))
print('4 x 4 Matrix:', multiply_matrices(Matrix_C, Matrix_C))
print('5 x 5 Matrix:', multiply_matrices(Matrix_D, Matrix_D))
run_time = time.time() - start
print('time: ', run_time)

print('Chained Matrix Multiplication:')
print(np.matmul(np.matmul(Matrix_A, Matrix_B), Matrix_A))
print(multiply_matrices(multiply_matrices(Matrix_A, Matrix_B), Matrix_A))

Results using NumPy's matmul:
2 x 2 Matrix: [[22 34]
 [46 74]]
4 x 4 Matrix: [[ 74  42  88 104]
 [127  90 148 152]
 [ 52  38  95  91]
 [ 90  54 103 125]]
5 x 5 Matrix: [[ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]]
time:  0.0
Results using custom matrix multiplication function:
2 x 2 Matrix: [[22 34]
 [46 74]]
4 x 4 Matrix: [[ 74  42  88 104]
 [127  90 148 152]
 [ 52  38  95  91]
 [ 90  54 103 125]]
5 x 5 Matrix: [[ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]
 [ 28  56  84 112 140 168 196]]
time:  0.0
Chained Matrix Multiplication:
[[248 360]
 [536 776]]
[[248 360]
 [536 776]]


## 2. Give the asymptotic time complexity of the above algorithm or your implementation (they should be the same). Justify and explain your answer

The time complexity of this algorithm is 𝑂(𝑛3)

#### Explanation:
 Initializing the result matrix: This step takes constant time 𝑂(1) as it involves creating a matrix of size 𝑛×𝑛.
 
 For the 'Nested Loops' for matrix multiplication:
 
   1.There are two nested loops iterating over each element of the resulting matrix 𝐶,each running from 0 to 𝑛−1.
    
   2.Inside the nested loops,there's a summation operation which runs 𝑛 times for each element of 𝐶.
    
   3.Thus,the total number of operations inside the nested loops is 𝑛×𝑛×𝑛=𝑛^3.
 
 #
Therefore, the dominant factor in the time complexity is the cubic term 𝑛^3.

Thus, the overall time complexity of the algorithm is 𝑂(𝑛^3).

# Exercise Two
## 1. Describe and explain the algorithm. It should contain at least the following:
#### - recursiveness: How is it recursive? What is (the criteria for) the base case? How does the recursion step reduce to the base case?
#### - divide-and-conquer : How does this algorithm fit into the divide-andconquer approach? Explain each step of divide, conquer, and combine for this algorithm (as in slide 8 / pdf page 16 of the lecture slides).

#
#### Explanation:

#### Recursiveness:

algorithm is recursive, calling itself to perform matrix multiplication on smaller sub-problems. It handles quarter-sized sub-matrices until reaching the base case, where the matrix size reduces to 1x1, simplifying multiplication to a single-element operation. 

The recursion divides each matrix into four equal-sized sub-matrices, halving the size with each recursive call until reaching the base case.

#### Divide-and-Conquer:
##### Divide: 
The algorithm splits the problem of multiplying two n x n matrices into smaller problems by dividing each matrix (A and B) into four sub-matrices.
##### Conquer: 
It recursively solves these smaller multiplication problems, recursively multiplying the sub-matrices until reaching the base case of single-element matrices.
##### Combine: 
After the recursive multiplications, the algorithm combines the results to form the final matrix by concatenating sub-matrix results. The resultant matrix is constructed by concatenating sub-matrices according to their positions.

# 

## 2. Implement the recursive algorithm in Python. 
Reflect on which steps of the pseudocode were straightforward to implement and which hid a lot of complexity behind their language.

In [15]:
import numpy as np

def partition_matrix(matrix):
    n = len(matrix)
    mid = n // 2
    top_left = [row[:mid] for row in matrix[:mid]]
    top_right = [row[mid:] for row in matrix[:mid]]
    bottom_left = [row[:mid] for row in matrix[mid:]]
    bottom_right = [row[mid:] for row in matrix[mid:]]
    return top_left, top_right, bottom_left, bottom_right

def add_matrices(A, B):
    return [[A[i][j] + B[i][j] for j in range(len(A[i]))] for i in range(len(A))]

def combine_matrices(top_left, top_right, bottom_left, bottom_right):
    top_half = [left + right for left, right in zip(top_left, top_right)]
    bottom_half = [left + right for left, right in zip(bottom_left, bottom_right)]
    return top_half + bottom_half

def recursive_multiply_matrices(A, B):
    n = len(A)
    if n == 1:
        return [[A[0][0] * B[0][0]]]
    else:
        A11, A12, A21, A22 = partition_matrix(A)
        B11, B12, B21, B22 = partition_matrix(B)
        M1 = add_matrices(recursive_multiply_matrices(A11, B11), recursive_multiply_matrices(A12, B21))
        M2 = add_matrices(recursive_multiply_matrices(A11, B12), recursive_multiply_matrices(A12, B22))
        M3 = add_matrices(recursive_multiply_matrices(A21, B11), recursive_multiply_matrices(A22, B21))
        M4 = add_matrices(recursive_multiply_matrices(A21, B12), recursive_multiply_matrices(A22, B22))
        return combine_matrices(M1, M2, M3, M4)


In [16]:
Matrix_E = np.array([[1, 3], [5, 7]])
Matrix_F = np.array([[2, 4], [6, 8]])
Matrix_G = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print("Results using recursive matrix multiplication:")
print('2 x 2 Matrix:', recursive_multiply_matrices(Matrix_E, Matrix_F))
print('4 x 4 Matrix:', recursive_multiply_matrices(Matrix_G, Matrix_G))

print('Chained Recursive Matrix Multiplication (2 x 2 Matrix):')
chained_result = recursive_multiply_matrices(recursive_multiply_matrices(Matrix_E, Matrix_F), Matrix_E)
print(chained_result)

Results using recursive matrix multiplication:
2 x 2 Matrix: [[20, 28], [52, 76]]
4 x 4 Matrix: [[90, 100, 110, 120], [202, 228, 254, 280], [314, 356, 398, 440], [426, 484, 542, 600]]
Chained Recursive Matrix Multiplication (2 x 2 Matrix):
[[160, 256], [432, 688]]


### Test and compare the practical speed with the non-recursive algorithm

In [19]:
import numpy as np
import time

Large_Matrix = np.array([[i for i in range(1, 65)] for _ in range(64)])

start_time = time.time()
result_basic = multiply_matrices(Large_Matrix, Large_Matrix)
basic_mul_time = (time.time() - start_time)

start_time = time.time()
result_recursive = recursive_multiply_matrices(Large_Matrix.tolist(), Large_Matrix.tolist())
recursive_mul_time = (time.time() - start_time)

print(f"Basic Multiply Time: {basic_mul_time:.4f} s, Recursive Multiply Time: {recursive_mul_time:.4f} s")

Basic Multiply Time: 0.0715 s, Recursive Multiply Time: 0.4071 s


## 3. Do a complexity analysis for the SMMRec algorithm. 
#### - First comment on the complexity of the base case, divide step, conquer step, and combine step separately, then put it all together.

##### Divide:
The algorithm divides each n x n matrix into four 𝑛/2×𝑛/2 sub-matrices.This step is simple,involving only indexing operations with a constant time complexity 𝑂(1).
##### Conquer:
The conquer step involves eight recursive calls to multiply the smaller 𝑛/2×𝑛/2 sub-matrices until reaching the base case of 1 x 1 matrices, which are directly multiplied in constant time.
##### Combine:
The results of the recursive multiplications are combined into the final matrix C using matrix addition, which has a complexity of 𝑂(𝑛^2).
##### Overall Complexity:
The recurrence relation for the algorithm is 𝑇(𝑛)=8𝑇(𝑛/2)+𝑂(𝑛^2). Solving this gives 𝑇(𝑛)=𝑂(𝑛^3), the same as the iterative approach but foundational for more advanced algorithms like Strassen's method. Notably, it paves the way for Strassen's algorithm, which significantly reduces the complexity to approximately 𝑂(𝑛log⁡27),enhancing efficiency for large matrices.

#

# Exercise Three

## 1. Reflect on the difference between (complexity of) addition/subtraction and multiplication on matrices.


Matrix addition and subtraction are straightforward operations for matrices of size 𝑛×𝑛. Each element from one matrix is added or subtracted from the corresponding element of the other matrix, resulting in 𝑛^2 total operations, leading to a computational complexity of 𝑂(𝑛^2).

Matrix multiplication is more complex. For each element in the resulting 𝑛×𝑛 matrix, 𝑛 multiplications and 𝑛−1 additions are needed. With 𝑛^2 elements to compute, the straightforward (naive) approach has a complexity of 𝑂(𝑛^3). Each element requires 2𝑛−1 operations, which aggregates to a much higher overall computational effort compared to addition or subtraction.

### Implement and test the algorithm

In [20]:
import numpy as np

def enhanced_matrix_split(matrix):
    size = len(matrix)
    mid_point = size // 2
    quadrant1 = [row[:mid_point] for row in matrix[:mid_point]]
    quadrant2 = [row[mid_point:] for row in matrix[:mid_point]]
    quadrant3 = [row[:mid_point] for row in matrix[mid_point:]]
    quadrant4 = [row[mid_point:] for row in matrix[mid_point:]]
    return quadrant1, quadrant2, quadrant3, quadrant4

def matrix_operation_add(submatrix1, submatrix2):
    return [[submatrix1[i][j] + submatrix2[i][j] for j in range(len(submatrix1))] for i in range(len(submatrix1))]

def matrix_operation_subtract(submatrix1, submatrix2):
    return [[submatrix1[i][j] - submatrix2[i][j] for j in range(len(submatrix1))] for i in range(len(submatrix1))]

def assemble_matrix(q1, q2, q3, q4):
    upper_half = [left + right for left, right in zip(q1, q2)]
    lower_half = [left + right for left, right in zip(q3, q4)]
    return upper_half + lower_half

def optimized_strassen_matrix_multiply(A, B):
    n = len(A)
    if n <= 2:  # Use the direct method for small matrices
        return recursive_multiply_matrices(A, B)
    else:
        mid = n // 2
        A11, A12, A21, A22 = enhanced_matrix_split(A)
        B11, B12, B21, B22 = enhanced_matrix_split(B)
        
        S1 = matrix_operation_add(A11, A22)
        S2 = matrix_operation_add(B11, B22)
        S3 = matrix_operation_add(A21, A22)
        S4 = B11
        S5 = A11
        S6 = matrix_operation_subtract(B12, B22)
        S7 = A22
        S8 = matrix_operation_subtract(B21, B11)
        S9 = matrix_operation_add(A11, A12)
        S10 = B22
        P1 = optimized_strassen_matrix_multiply(S1, S2)
        P2 = optimized_strassen_matrix_multiply(S3, S4)
        P3 = optimized_strassen_matrix_multiply(S5, S6)
        P4 = optimized_strassen_matrix_multiply(S7, S8)
        P5 = optimized_strassen_matrix_multiply(S9, S10)
        Q1 = matrix_operation_add(matrix_operation_subtract(matrix_operation_add(P1, P4), P5), P2)
        Q2 = matrix_operation_add(P3, P5)
        Q3 = matrix_operation_add(P2, P4)
        Q4 = matrix_operation_subtract(matrix_operation_subtract(matrix_operation_add(P1, P3), P2), P5)

        return assemble_matrix(Q1, Q2, Q3, Q4)

In [22]:
Matrix_H = np.array([[1, 3], [5, 7]])
Matrix_I = np.array([[2, 4], [6, 8]])
Matrix_J = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print("Results using Strassen's algorithm:")
print('2 x 2 Matrix:', optimized_strassen_matrix_multiply(Matrix_H, Matrix_I))
print('4 x 4 Matrix:', optimized_strassen_matrix_multiply(Matrix_J, Matrix_J))

Results using Strassen's algorithm:
2 x 2 Matrix: [[20, 28], [52, 76]]
4 x 4 Matrix: [[604, 688, 110, 120], [764, 880, 254, 280], [314, 356, 136, 136], [426, 484, 72, 72]]


### Compare the practical speed with the recursive algorithm

In [23]:
Performance_Matrix = np.array([[i for i in range(1, 129)] for _ in range(128)])

start_time = time.time()
result_from_basic = multiply_matrices(Performance_Matrix, Performance_Matrix)
time_for_basic = (time.time() - start_time)

start_time = time.time()
result_from_recursive = recursive_multiply_matrices(Performance_Matrix.tolist(), Performance_Matrix.tolist())
time_for_recursive = (time.time() - start_time)

print(f"Time for Basic Multiplication: {time_for_basic:.4f} s, Time for Recursive Multiplication: {time_for_recursive:.4f} s")

Time for Basic Multiplication: 0.5441 s, Time for Recursive Multiplication: 3.5106 s



## 2.Do a complexity analysis of the Strassen algorithm.
#### - Instead of starting from scratch, you can also take your result from Exercise 2 and adapt to the optimisation; explain what changes in the complexity formula with these optimisations.

##### Standard Recursive Matrix Multiplication: 
The traditional recursive approach to matrix multiplication has a complexity recurrence of 𝑇(𝑛)=8𝑇(𝑛/2)+𝑂(𝑛^2), which resolves to 𝑂(𝑛^3) according to the Master Theorem.
##### Strassen’s Algorithm: 
Strassen’s algorithm reduces the number of recursive matrix multiplications from 8 to 7 by rearranging and combining operations ingeniously, adding more additions and subtractions but fewer multiplications. This results in a new complexity recurrence: 

𝑇(𝑛)=7𝑇(𝑛/2)+𝑂(𝑛^2).

##### Complexity Analysis: 
By applying the Master Theorem to Strassen's recurrence, the complexity becomes 𝑇(𝑛)=𝑂(𝑛log⁡27)≈𝑂(𝑛2.81).This optimization demonstrates a significant reduction from the 𝑂(𝑛^3) complexity of the standard recursive approach, underscoring the efficiency gains achievable through Strassen’s method.
